obj-m += rust_bench.o
KERN_SRC = ~/rust-for-linux

all:
	make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C $(KERN_SRC) M=$(PWD) modules CC=$(CC)

clean:
	make -C ${KERN_SRC} M=$(PWD) CC=$(CC) clean
