//! Allocation APIs exported by UniAlloc.

#[cfg(all(feature = "lifetime_hugepage", not(feature = "fixed_heap")))]
pub(crate) mod lifetime_hugepage;
pub mod type_aware;
pub mod type_isolation;

#[cfg(all(feature = "lifetime_hugepage", not(feature = "fixed_heap")))]
pub use lifetime_hugepage::{
    lifetime_hugepage_adaptive_site_force_track_all_disable,
    lifetime_hugepage_adaptive_site_force_track_all_enable,
    lifetime_hugepage_adaptive_site_force_track_all_enabled,
    lifetime_hugepage_adaptive_site_recording_disable,
    lifetime_hugepage_adaptive_site_recording_enable,
    lifetime_hugepage_adaptive_site_recording_enabled, lifetime_hugepage_adaptive_site_snapshot,
    lifetime_hugepage_advance_epoch, lifetime_hugepage_backend, lifetime_hugepage_configure,
    lifetime_hugepage_configure_with_backend, lifetime_hugepage_phase_flush_current_thread,
    lifetime_hugepage_policy, lifetime_hugepage_stats_reset, lifetime_hugepage_stats_snapshot,
    lifetime_hugepage_trim_retained_empty_extents, LifetimeAdaptiveSiteSnapshot,
    LifetimeHugepagePolicy, LifetimeHugepageStatsSnapshot, LifetimePageBackend,
    LIFETIME_ADAPTIVE_SITE_SNAPSHOT_ABI_VERSION, LIFETIME_ADAPTIVE_SITE_SNAPSHOT_CAPACITY,
    LIFETIME_HUGEPAGE_EXTENT_BYTES, LIFETIME_HUGEPAGE_IDENTITY_REGION_BYTES,
};

pub use type_isolation::{
    __unialloc_alloc_layout_with_metadata, __unialloc_alloc_layout_with_metadata_hints,
    __unialloc_alloc_layout_with_metadata_hints_local, __unialloc_alloc_layout_with_metadata_local,
    __unialloc_alloc_with_metadata, __unialloc_alloc_with_metadata_hints,
    __unialloc_alloc_with_metadata_hints_local, __unialloc_alloc_with_metadata_local,
    __unialloc_alloc_zeroed_layout_with_metadata,
    __unialloc_alloc_zeroed_layout_with_metadata_hints,
    __unialloc_alloc_zeroed_layout_with_metadata_hints_local,
    __unialloc_alloc_zeroed_layout_with_metadata_local, __unialloc_dealloc_layout_with_metadata,
    __unialloc_dealloc_layout_with_metadata_hints,
    __unialloc_dealloc_layout_with_metadata_hints_local,
    __unialloc_dealloc_layout_with_metadata_local, __unialloc_dealloc_with_metadata,
    __unialloc_dealloc_with_metadata_hints, __unialloc_dealloc_with_metadata_hints_local,
    __unialloc_dealloc_with_metadata_local, __unialloc_realloc_layout_with_metadata,
    __unialloc_realloc_layout_with_metadata_hints,
    __unialloc_realloc_layout_with_metadata_hints_local,
    __unialloc_realloc_layout_with_metadata_local, __unialloc_realloc_with_metadata,
    __unialloc_realloc_with_metadata_hints, __unialloc_realloc_with_metadata_hints_local,
    __unialloc_realloc_with_metadata_local, __unialloc_realloc_with_split_metadata,
    __unialloc_realloc_with_split_metadata_hints,
    __unialloc_semantic_auto_compiler_metadata_enable,
    __unialloc_semantic_auto_compiler_metadata_stream_enable,
    __unialloc_semantic_auto_metadata_disable, __unialloc_semantic_auto_metadata_enable,
    __unialloc_semantic_box_slice_into_vec, __unialloc_semantic_fallback_attribution_snapshot,
    __unialloc_semantic_fallback_attribution_snapshot_abi_version,
    __unialloc_semantic_fallback_attribution_snapshot_checked,
    __unialloc_semantic_fallback_attribution_snapshot_size,
    __unialloc_semantic_metadata_validation_snapshot,
    __unialloc_semantic_metadata_validation_snapshot_abi_version,
    __unialloc_semantic_metadata_validation_snapshot_checked,
    __unialloc_semantic_metadata_validation_snapshot_size,
    __unialloc_semantic_scope_depth_snapshot, __unialloc_semantic_scope_enter,
    __unialloc_semantic_scope_enter_hints, __unialloc_semantic_scope_exit,
    __unialloc_semantic_scope_pop, __unialloc_semantic_scope_push,
    __unialloc_semantic_scope_push_hints, __unialloc_semantic_scope_push_hints_local,
    __unialloc_semantic_scope_push_local, __unialloc_semantic_stats_reset,
    __unialloc_semantic_stats_snapshot, __unialloc_semantic_stats_snapshot_abi_version,
    __unialloc_semantic_stats_snapshot_checked, __unialloc_semantic_stats_snapshot_size,
    __unialloc_semantic_type_stats_snapshot, __unialloc_semantic_type_stats_snapshot_abi_version,
    __unialloc_semantic_type_stats_snapshot_checked,
    __unialloc_semantic_type_stats_snapshot_record_size, active_allocation_metadata,
    allocate_semantic_slice, auto_allocation_metadata, auto_deallocation_metadata,
    delayed_free_snapshot, lifetime_placement_class, metadata_pointer_auth_runtime_probe,
    metadata_segregation_side_cache_snapshot, restore_active_metadata,
    semantic_allocation_layout_validation_snapshot, semantic_auto_compiler_metadata_enable,
    semantic_auto_compiler_metadata_enabled, semantic_auto_compiler_metadata_stream_enable,
    semantic_auto_compiler_metadata_stream_enabled,
    semantic_auto_compiler_metadata_stream_thread_local_recovery_enable,
    semantic_auto_compiler_metadata_thread_local_recovery_enable, semantic_auto_metadata_disable,
    semantic_auto_metadata_enable, semantic_auto_metadata_enabled,
    semantic_auto_metadata_type_id_basis, semantic_fallback_attribution_snapshot,
    semantic_layout_id, semantic_metadata_validation_snapshot,
    semantic_ownership_transfer_snapshot, semantic_runtime_slow_path_enabled,
    semantic_scope_depth_snapshot, semantic_stats_last_wrong_identity_retained_ptr,
    semantic_stats_recording_disable, semantic_stats_recording_enable,
    semantic_stats_recording_enabled, semantic_stats_reset, semantic_stats_snapshot,
    semantic_type_id, semantic_type_stats_recording_disable, semantic_type_stats_recording_enable,
    semantic_type_stats_recording_enabled, semantic_type_stats_snapshot, set_active_metadata,
    take_auto_deallocation_metadata, type_cache_admission_stats_reset,
    type_cache_admission_stats_snapshot, type_isolation_side_cache_snapshot,
    with_rust_type_metadata_at, with_semantic_metadata, AllocationMetadata, DelayedFreeSnapshot,
    LifetimePlacementClass, MetadataPointerAuthRuntimeProbe, MetadataSegregationSideCacheSnapshot,
    SemanticAlloc, SemanticAllocationLayoutValidationSnapshot, SemanticFallbackAttributionSnapshot,
    SemanticMetadataValidationSnapshot, SemanticOwnershipTransferSnapshot,
    SemanticScopeDepthSnapshot, SemanticStatsSnapshot, SemanticTypeStatsSnapshot,
    TypeCacheAdmissionCounterSnapshot, TypeCacheAdmissionStatsSnapshot,
    TypeIsolationSideCacheSnapshot, AUTO_LAYOUT_MODULE_ID, FLAG_DELAYED_FREE,
    FLAG_FORCE_INITIALIZE, FLAG_GUARD_PAGES, FLAG_HUGEPAGE_METADATA, FLAG_MEMORY_TAGGING,
    FLAG_METADATA_PROTECTION, FLAG_METADATA_SEGREGATED, FLAG_POINTER_AUTH, FLAG_TYPE_ISOLATED,
    LIFETIME_HINT_BORROWED_VEC_RESERVE_OBSERVE, LIFETIME_HINT_BOUNDED_PROCESS_LONG,
    LIFETIME_HINT_DYNAMIC_BUFFER_OBSERVE, LIFETIME_HINT_EPHEMERAL, LIFETIME_HINT_LOCAL_DROP_FACT,
    LIFETIME_HINT_LONG_LIVED, LIFETIME_HINT_PROVEN_EPHEMERAL, LIFETIME_HINT_PROVEN_LONG_LIVED,
    MIN_TYPE_CACHE_OBJECT_SIZE, PLACEMENT_HINT_CROSS_THREAD_RECOVERY,
    PLACEMENT_HINT_LOCAL_SCOPE_NO_RECOVERY, SEMANTIC_FALLBACK_ATTRIBUTION_SNAPSHOT_ABI_VERSION,
    SEMANTIC_METADATA_VALIDATION_SNAPSHOT_ABI_VERSION, SEMANTIC_STATS_SNAPSHOT_ABI_VERSION,
    SEMANTIC_TYPE_STATS_SNAPSHOT_ABI_VERSION, UNKNOWN_SEMANTIC_ID,
};

#[cfg(not(feature = "fixed_heap"))]
pub use type_isolation::{
    hugepage_metadata_side_cache_backing_snapshot, hugepage_metadata_side_cache_snapshot,
    HugepageMetadataSideCacheSnapshot,
};
